import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './style.css';
import { LINES } from './data/lines.js';

const BA_CENTER = [-34.6037, -58.4416];
const HUB_RADIUS_M = 300; // terminals of different lines this close share one pin

const JURISDICTIONS = {
  nacional: 'Nacionales',
  provincial: 'Provinciales',
  municipal: 'Municipales',
};

// Placeholder palette until each line gets its real livery colors.
const PALETTE = [
  '#e8452c', '#1f6feb', '#2da44e', '#8250df', '#d4a72c', '#cf222e',
  '#0a7ea4', '#bf3989', '#6e7781', '#fb8f44', '#1b7c83', '#953800',
];

const km = new Intl.NumberFormat('es-AR', { maximumFractionDigits: 1 });

// ---------- Map ----------
// CARTO's light basemap keeps streets readable but quiet, so routes stand out.
const map = L.map('map', { zoomControl: false }).setView(BA_CENTER, 11);
L.control.zoom({ position: 'bottomleft' }).addTo(map);
// CARTO requires an API key on basemap tiles (set VITE_CARTO_KEY in .env).
const cartoKey = import.meta.env.VITE_CARTO_KEY;
L.tileLayer(`https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png${cartoKey ? `?key=${cartoKey}` : ''}`, {
  maxZoom: 20,
  subdomains: 'abcd',
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    + ' &copy; <a href="https://carto.com/attributions">CARTO</a>'
    + ' · Recorridos: <a href="https://datos.transporte.gob.ar/">Secretaría de Transporte</a>',
}).addTo(map);
const routeRenderer = L.canvas({ padding: 0.5 }); // hundreds of routes are much faster on canvas

// Filled in at boot from public/data/lines.json, plus the extras in src/data/lines.js.
const lines = new Map();
const extras = new Map(LINES.map((l) => [l.line, l]));

// ---------- Route data (generated by scripts/build-routes.mjs) ----------
const routeCache = new Map();
function loadRoutes(line) {
  if (!routeCache.has(line)) {
    routeCache.set(line, fetch(`/data/routes/${line}.json`).then((r) => {
      if (!r.ok) throw new Error(`No hay recorrido para la línea ${line}`);
      return r.json();
    }));
  }
  return routeCache.get(line);
}

// ---------- Status pill ----------
const status = document.getElementById('status');
let statusTimer;
function showStatus(text, { isError = false, autoHide = false } = {}) {
  clearTimeout(statusTimer);
  status.textContent = text;
  status.classList.toggle('error', isError);
  status.hidden = !text;
  if (autoHide) statusTimer = setTimeout(() => showStatus(''), 5000);
}

// ---------- Jurisdiction filter ----------
const filterEl = document.getElementById('jurisdiction-filter');
const enabled = new Set(Object.keys(JURISDICTIONS));
const isVisible = (line) => enabled.has(lines.get(line).jurisdiction);

function renderFilter() {
  const counts = Object.fromEntries(Object.keys(JURISDICTIONS).map((j) => [j, 0]));
  for (const l of lines.values()) counts[l.jurisdiction]++;
  filterEl.replaceChildren(...Object.entries(JURISDICTIONS).map(([j, label]) => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'filter';
    btn.setAttribute('aria-pressed', String(enabled.has(j)));
    btn.innerHTML = `${label} <span class="filter-count">${counts[j]}</span>`;
    btn.addEventListener('click', () => {
      if (enabled.has(j)) enabled.delete(j);
      else enabled.add(j);
      btn.setAttribute('aria-pressed', String(enabled.has(j)));
      if (activeLine && !isVisible(activeLine)) closePanel();
      drawHubs();
      if (toggle.checked) showAllRoutes();
    });
    return btn;
  }));
}

// ---------- Terminal pins ----------
function buildHubs() {
  const hubs = [];
  for (const [line, data] of lines) {
    if (!isVisible(line)) continue;
    for (const t of data.terminals) {
      const at = [t.lat, t.lng];
      let hub = hubs.find((h) => map.distance(h.at, at) < HUB_RADIUS_M);
      if (!hub) hubs.push((hub = { at, stops: [] }));
      hub.stops.push({ line, branches: t.branches });
    }
  }
  return hubs;
}

function chipHtml(stop) {
  const { color } = lines.get(stop.line);
  const title = `Línea ${stop.line} · ramal${stop.branches.length > 1 ? 'es' : ''} ${stop.branches.join(', ')}`;
  return `<button type="button" class="chip" data-line="${stop.line}" style="--pin-color:${color}" title="${title}">${stop.line}</button>`;
}

// Zoomed out there are far too many terminals for numbered pins, so they
// start as dots (a count when several lines share one) and become pins up close.
const PIN_ZOOM = 14;
const hubLayer = L.layerGroup().addTo(map);
let hubs = [];
let showingPins = null;

function hubIcon(hub, asPin) {
  if (asPin) {
    return L.divIcon({
      className: 'pin-icon',
      html: `<div class="pin">${hub.stops.map(chipHtml).join('')}</div>`,
      iconSize: [0, 0],
    });
  }
  const [first] = hub.stops;
  const n = hub.stops.length;
  const style = n === 1 ? ` style="--pin-color:${lines.get(first.line).color}"` : '';
  return L.divIcon({
    className: 'pin-icon',
    html: `<div class="dot${n > 1 ? ' dot-multi' : ''}"${style}>${n > 1 ? n : ''}</div>`,
    iconSize: [0, 0],
  });
}

function hubTitle(hub) {
  return hub.stops.length === 1
    ? `Línea ${hub.stops[0].line}`
    : `${hub.stops.length} líneas: ${hub.stops.map((s) => s.line).join(', ')}`;
}

function renderHubs() {
  showingPins = map.getZoom() >= PIN_ZOOM;
  hubLayer.clearLayers();
  for (const hub of hubs) {
    const marker = L.marker(hub.at, {
      icon: hubIcon(hub, showingPins),
      riseOnHover: true,
      keyboard: false,
      title: showingPins ? '' : hubTitle(hub),
    });
    marker.on('click', (e) => {
      if (!showingPins) {
        map.setView(hub.at, PIN_ZOOM);
        return;
      }
      const chip = e.originalEvent.target.closest('.chip');
      if (chip) openPanel(chip.dataset.line);
    });
    marker.addTo(hubLayer);
  }
  markActiveChips(activeLine);
}

function drawHubs() {
  hubs = buildHubs();
  renderHubs();
}

map.on('zoomend', () => {
  if ((map.getZoom() >= PIN_ZOOM) !== showingPins) renderHubs();
});

function markActiveChips(line) {
  document.querySelectorAll('.chip').forEach((c) => {
    c.classList.toggle('is-active', c.dataset.line === line);
    c.classList.toggle('is-dimmed', line !== null && c.dataset.line !== line);
  });
}

// ---------- All routes (toggle) ----------
const toggle = document.getElementById('routes-toggle');
const routeLayers = new Map(); // line -> L.GeoJSON, created on first show
const allRoutesLayer = L.layerGroup();
const ROUTE_OPACITY = 0.55;
const ROUTE_OPACITY_DIMMED = 0.12; // while one line is selected

function dimOtherRoutes(dim) {
  routeLayers.forEach((layer) => layer.setStyle({ opacity: dim ? ROUTE_OPACITY_DIMMED : ROUTE_OPACITY }));
}

async function showAllRoutes() {
  const visible = [...lines.keys()].filter(isVisible);
  const missing = visible.filter((line) => !routeLayers.has(line));
  if (missing.length) showStatus(`Cargando ${missing.length} recorridos…`);

  const results = await Promise.allSettled(missing.map(async (line) => {
    const fc = await loadRoutes(line);
    const layer = L.geoJSON(fc, {
      renderer: routeRenderer,
      style: { color: lines.get(line).color, weight: 2, opacity: activeLine ? ROUTE_OPACITY_DIMMED : ROUTE_OPACITY },
    })
      .on('click', (e) => {
        L.DomEvent.stopPropagation(e);
        openPanel(line);
      })
      .bindTooltip(`Línea ${line}`, { sticky: true });
    routeLayers.set(line, layer);
  }));
  const failed = missing.filter((_, i) => results[i].status === 'rejected');
  showStatus(failed.length ? `Sin recorrido: ${failed.join(', ')}` : '', { isError: true, autoHide: true });

  if (!toggle.checked) return; // switched off while loading
  allRoutesLayer.clearLayers();
  for (const line of visible) routeLayers.get(line)?.addTo(allRoutesLayer);
  allRoutesLayer.addTo(map);
}

toggle.addEventListener('change', () => {
  if (toggle.checked) showAllRoutes();
  else allRoutesLayer.remove();
});

// ---------- Side panel ----------
const panel = document.getElementById('panel');
const panelBadge = document.getElementById('panel-badge');
const panelTitle = document.getElementById('panel-title');
const panelSub = document.getElementById('panel-sub');
const branchPicker = document.getElementById('branch-picker');
const branchInfo = document.getElementById('branch-info');
const panelBody = document.getElementById('panel-body');
const focusLayer = L.layerGroup().addTo(map);
let activeLine = null;

function wikipediaUrl(title) {
  // The mobile site fits a narrow panel much better than the desktop one.
  return `https://es.m.wikipedia.org/wiki/${encodeURIComponent(title.replaceAll(' ', '_'))}`;
}

function describeBranches(line, branch) {
  const { branches } = lines.get(line);
  if (branch !== null) {
    const { ida, vuelta } = branches[branch];
    return [ida && `Ida ${km.format(ida)} km`, vuelta && `Vuelta ${km.format(vuelta)} km`].filter(Boolean).join(' · ');
  }
  const lengths = Object.values(branches).flatMap((b) => Object.values(b));
  const min = Math.min(...lengths);
  const max = Math.max(...lengths);
  const n = Object.keys(branches).length;
  const range = min === max ? `${km.format(max)} km` : `de ${km.format(min)} a ${km.format(max)} km`;
  return `${n} ramal${n > 1 ? 'es' : ''} · recorridos ${range}`;
}

function drawFocus(fc, line, branch) {
  focusLayer.clearLayers();
  branchInfo.textContent = describeBranches(line, branch);
  const features = fc.features.filter((f) => branch === null || f.properties.ramal === branch);
  const layer = L.geoJSON({ type: 'FeatureCollection', features }, {
    renderer: routeRenderer,
    style: { color: lines.get(line).color, weight: 5, opacity: 0.9 },
    interactive: false,
  }).addTo(focusLayer);
  if (!features.length) return;
  // On a phone the panel covers the map, so don't pad for it.
  const panelCover = panel.offsetWidth < window.innerWidth ? panel.offsetWidth : 0;
  map.fitBounds(layer.getBounds(), { paddingTopLeft: [40, 40], paddingBottomRight: [panelCover + 40, 40] });
}

function renderBranchPicker(fc, line) {
  const branches = Object.keys(lines.get(line).branches);
  const options = branches.length > 1 ? [null, ...branches] : branches;
  const label = document.createElement('span');
  label.className = 'branch-label';
  label.textContent = branches.length > 1 ? 'Ramales' : 'Ramal';

  const buttons = options.map((branch, i) => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'branch';
    btn.textContent = branch ?? 'Todos';
    btn.setAttribute('aria-pressed', String(i === 0));
    btn.addEventListener('click', () => {
      buttons.forEach((b) => b.setAttribute('aria-pressed', String(b === btn)));
      drawFocus(fc, line, branch);
    });
    return btn;
  });
  branchPicker.replaceChildren(label, ...buttons);
  branchPicker.hidden = false;
  branchInfo.hidden = false;
  return options[0];
}

async function openPanel(line) {
  const data = lines.get(line);
  activeLine = line;
  markActiveChips(line);
  dimOtherRoutes(true);

  panel.style.setProperty('--pin-color', data.color);
  panelBadge.textContent = line;
  panelTitle.textContent = `Línea ${line}`;
  const jurisdiction = `Línea ${data.jurisdiction}`;
  panelSub.textContent = data.company ? `${data.company} · ${jurisdiction}` : jurisdiction;

  panelBody.replaceChildren();
  if (data.wikipedia) {
    const frame = document.createElement('iframe');
    frame.src = wikipediaUrl(data.wikipedia);
    frame.title = `Wikipedia: ${data.wikipedia}`;
    frame.referrerPolicy = 'no-referrer';
    panelBody.append(frame);
  } else {
    const empty = document.createElement('div');
    empty.className = 'panel-empty';
    empty.textContent = 'Todavía no tenemos información de esta línea.';
    panelBody.append(empty);
  }

  panel.classList.add('is-open');
  panel.setAttribute('aria-hidden', 'false');

  branchPicker.hidden = true;
  branchInfo.hidden = true;
  focusLayer.clearLayers();
  try {
    const fc = await loadRoutes(line);
    if (activeLine !== line) return; // another line was opened meanwhile
    drawFocus(fc, line, renderBranchPicker(fc, line));
  } catch (err) {
    console.error(err);
    showStatus(err.message, { isError: true, autoHide: true });
  }
}

function closePanel() {
  activeLine = null;
  markActiveChips(null);
  dimOtherRoutes(false);
  focusLayer.clearLayers();
  panel.classList.remove('is-open');
  panel.setAttribute('aria-hidden', 'true');
}

document.getElementById('panel-close').addEventListener('click', closePanel);
document.addEventListener('keydown', (e) => e.key === 'Escape' && closePanel());
map.on('click', closePanel);

// ---------- Boot ----------
fetch('/data/lines.json')
  .then((r) => r.json())
  .then((index) => {
    Object.entries(index).forEach(([line, data], i) => {
      lines.set(line, { ...data, ...extras.get(line), line, color: PALETTE[i % PALETTE.length] });
    });
    renderFilter();
    drawHubs();
  })
  .catch((err) => {
    console.error(err);
    showStatus('No se pudieron cargar las líneas.', { isError: true });
  });
