import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './style.css';
import { LINES } from './data/lines.js';

const BA_CENTER = [-34.6037, -58.4416];
const HUB_RADIUS_M = 300; // terminals of different lines this close share one pin

// Placeholder palette until each line gets its real livery colors.
const PALETTE = [
  '#e8452c', '#1f6feb', '#2da44e', '#8250df', '#d4a72c', '#cf222e',
  '#0a7ea4', '#bf3989', '#6e7781', '#fb8f44', '#1b7c83', '#953800',
];

const map = L.map('map', { zoomControl: false }).setView(BA_CENTER, 11);
L.control.zoom({ position: 'bottomleft' }).addTo(map);
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
  maxZoom: 19,
  attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    + ' · Recorridos: <a href="https://datos.transporte.gob.ar/">Secretaría de Transporte</a>',
}).addTo(map);

const lines = new Map(LINES.map((l, i) => [l.line, { ...l, color: PALETTE[i % PALETTE.length] }]));

// ---------- Route data (generated by scripts/build-routes.mjs) ----------
const routeCache = new Map();
function loadRoutes(line) {
  if (!routeCache.has(line)) {
    routeCache.set(line, fetch(`/data/routes/${line}.json`).then((r) => {
      if (!r.ok) throw new Error(`No hay recorrido para la línea ${line}`);
      return r.json();
    }));
  }
  return routeCache.get(line);
}

const branchesOf = (fc) => [...new Set(fc.features.map((f) => f.properties.ramal))];

// ---------- Status pill ----------
const status = document.getElementById('status');
let statusTimer;
function showStatus(text, { isError = false, autoHide = false } = {}) {
  clearTimeout(statusTimer);
  status.textContent = text;
  status.classList.toggle('error', isError);
  status.hidden = !text;
  if (autoHide) statusTimer = setTimeout(() => showStatus(''), 5000);
}

// ---------- Terminal pins ----------
function buildHubs(terminalsByLine) {
  const hubs = [];
  for (const [line, terminals] of Object.entries(terminalsByLine)) {
    if (!lines.has(line)) continue;
    for (const t of terminals) {
      const at = [t.lat, t.lng];
      let hub = hubs.find((h) => map.distance(h.at, at) < HUB_RADIUS_M);
      if (!hub) hubs.push((hub = { at, stops: [] }));
      hub.stops.push({ line, branches: t.branches });
    }
  }
  // Keep the order of LINES inside each pin.
  const order = [...lines.keys()];
  hubs.forEach((h) => h.stops.sort((a, b) => order.indexOf(a.line) - order.indexOf(b.line)));
  return hubs;
}

function chipHtml(stop) {
  const { color } = lines.get(stop.line);
  const title = `Línea ${stop.line} · ramal${stop.branches.length > 1 ? 'es' : ''} ${stop.branches.join(', ')}`;
  return `<button type="button" class="chip" data-line="${stop.line}" style="--pin-color:${color}" title="${title}">${stop.line}</button>`;
}

function drawHubs(hubs) {
  for (const hub of hubs) {
    const icon = L.divIcon({
      className: 'pin-icon',
      html: `<div class="pin">${hub.stops.map(chipHtml).join('')}</div>`,
      iconSize: [0, 0],
    });
    L.marker(hub.at, { icon, riseOnHover: true, keyboard: false })
      .on('click', (e) => {
        const chip = e.originalEvent.target.closest('.chip');
        if (chip) openPanel(chip.dataset.line);
      })
      .addTo(map);
  }
}

function markActiveChips(line) {
  document.querySelectorAll('.chip').forEach((c) => {
    c.classList.toggle('is-active', c.dataset.line === line);
    c.classList.toggle('is-dimmed', line !== null && c.dataset.line !== line);
  });
}

// ---------- All routes (toggle) ----------
const allRoutesLayer = L.layerGroup();
const toggle = document.getElementById('routes-toggle');
let allRoutesLoaded = false;

async function showAllRoutes() {
  if (!allRoutesLoaded) {
    showStatus('Cargando recorridos…');
    const lineIds = [...lines.keys()];
    const results = await Promise.allSettled(lineIds.map(async (line) => {
      const fc = await loadRoutes(line);
      L.geoJSON(fc, { style: { color: lines.get(line).color, weight: 2.5, opacity: 0.6 } })
        .on('click', (e) => {
          L.DomEvent.stopPropagation(e);
          openPanel(line);
        })
        .bindTooltip(`Línea ${line}`, { sticky: true })
        .addTo(allRoutesLayer);
    }));
    const failed = lineIds.filter((_, i) => results[i].status === 'rejected');
    allRoutesLoaded = true;
    showStatus(failed.length ? `Sin recorrido: ${failed.join(', ')}` : '', { isError: true, autoHide: true });
  }
  if (toggle.checked) allRoutesLayer.addTo(map);
}

toggle.addEventListener('change', () => {
  if (toggle.checked) showAllRoutes();
  else allRoutesLayer.remove();
});

// ---------- Side panel ----------
const panel = document.getElementById('panel');
const panelBadge = document.getElementById('panel-badge');
const panelTitle = document.getElementById('panel-title');
const panelSub = document.getElementById('panel-sub');
const branchPicker = document.getElementById('branch-picker');
const panelBody = document.getElementById('panel-body');
const focusLayer = L.layerGroup().addTo(map);
let activeLine = null;

function wikipediaUrl(title) {
  // The mobile site fits a narrow panel much better than the desktop one.
  return `https://es.m.wikipedia.org/wiki/${encodeURIComponent(title.replaceAll(' ', '_'))}`;
}

function drawFocus(fc, line, branch) {
  focusLayer.clearLayers();
  const features = fc.features.filter((f) => branch === null || f.properties.ramal === branch);
  const layer = L.geoJSON({ type: 'FeatureCollection', features }, {
    style: { color: lines.get(line).color, weight: 5, opacity: 0.9 },
    interactive: false,
  }).addTo(focusLayer);
  if (!features.length) return;
  // On a phone the panel covers the map, so don't pad for it.
  const panelCover = panel.offsetWidth < window.innerWidth ? panel.offsetWidth : 0;
  map.fitBounds(layer.getBounds(), { paddingTopLeft: [40, 40], paddingBottomRight: [panelCover + 40, 40] });
}

function renderBranchPicker(fc, line) {
  const branches = branchesOf(fc);
  const options = branches.length > 1 ? [null, ...branches] : branches;
  const label = document.createElement('span');
  label.className = 'branch-label';
  label.textContent = branches.length > 1 ? 'Ramales' : 'Ramal';

  const buttons = options.map((branch, i) => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'branch';
    btn.textContent = branch ?? 'Todos';
    btn.setAttribute('aria-pressed', String(i === 0));
    btn.addEventListener('click', () => {
      buttons.forEach((b) => b.setAttribute('aria-pressed', String(b === btn)));
      drawFocus(fc, line, branch);
    });
    return btn;
  });
  branchPicker.replaceChildren(label, ...buttons);
  branchPicker.hidden = false;
}

async function openPanel(line) {
  const data = lines.get(line);
  activeLine = line;
  markActiveChips(line);

  panel.style.setProperty('--pin-color', data.color);
  panelBadge.textContent = line;
  panelTitle.textContent = `Línea ${line}`;
  panelSub.textContent = data.company ?? '';

  panelBody.replaceChildren();
  if (data.wikipedia) {
    const frame = document.createElement('iframe');
    frame.src = wikipediaUrl(data.wikipedia);
    frame.title = `Wikipedia: ${data.wikipedia}`;
    frame.referrerPolicy = 'no-referrer';
    panelBody.append(frame);
  } else {
    const empty = document.createElement('div');
    empty.className = 'panel-empty';
    empty.textContent = 'Todavía no tenemos información de esta línea.';
    panelBody.append(empty);
  }

  panel.classList.add('is-open');
  panel.setAttribute('aria-hidden', 'false');

  branchPicker.hidden = true;
  focusLayer.clearLayers();
  try {
    const fc = await loadRoutes(line);
    if (activeLine !== line) return; // another line was opened meanwhile
    renderBranchPicker(fc, line);
    drawFocus(fc, line, null);
  } catch (err) {
    console.error(err);
    showStatus(err.message, { isError: true, autoHide: true });
  }
}

function closePanel() {
  activeLine = null;
  markActiveChips(null);
  focusLayer.clearLayers();
  panel.classList.remove('is-open');
  panel.setAttribute('aria-hidden', 'true');
}

document.getElementById('panel-close').addEventListener('click', closePanel);
document.addEventListener('keydown', (e) => e.key === 'Escape' && closePanel());
map.on('click', closePanel);

// ---------- Boot ----------
fetch('/data/terminals.json')
  .then((r) => r.json())
  .then((terminals) => {
    const hubs = buildHubs(terminals);
    drawHubs(hubs);
    if (hubs.length) map.fitBounds(L.latLngBounds(hubs.map((h) => h.at)), { padding: [48, 48] });
  })
  .catch((err) => {
    console.error(err);
    showStatus('No se pudieron cargar las terminales.', { isError: true });
  });
